name       : plasma-wayland-protocols
version    : 1.3.0
release    : 4
source     :
    - https://cdn.download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-1.3.0.tar.xz : 0daa2362f2e0d15f79e0e006e8d7f1908e88e37b5c5208b40c9cb0d4d6dca9b5
homepage   : https://kde.org/plasma-desktop
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma Specific Protocols for Wayland
description: |
    Plasma Specific Protocols for Wayland
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
