name       : plasma-wayland-protocols
version    : 1.2.1
release    : 3
source     :
    - https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-v1.2.1.tar.xz : 287b90903f9a7f394c75e75cb187426862eaf64a92f1be7e2ef68e99fd8cbaaa
homepage   : https://kde.org/plasma-desktop
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma Specific Protocols for Wayland
description: |
    Plasma Specific Protocols for Wayland
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
