name       : plasma-wayland-protocols
version    : 1.5.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-1.5.0.tar.xz : ccc9fc20d7a130edbfb233c33b1325740ac01b2640aa37a5c544edbfba18a833
homepage   : https://kde.org/plasma-desktop
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma Specific Protocols for Wayland
description: |
    Plasma Specific Protocols for Wayland
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
